# Generated by Django 2.1.5 on 2019-03-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('rssid', models.CharField(max_length=200, verbose_name='ID')),
                ('published', models.DateField(verbose_name='Published')),
                ('update', models.DateField(verbose_name='Updated')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'RSS Entry',
                'verbose_name_plural': 'RSS Entries',
            },
        ),
        migrations.CreateModel(
            name='RSSFeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
            },
        ),
        migrations.AddField(
            model_name='rssentries',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snotra_rss.RSSFeeds'),
        ),
    ]
