# Generated by Django 2.2 on 2019-04-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('passwd', models.CharField(max_length=40, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
            },
        ),
        migrations.CreateModel(
            name='TwitterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=40)),
                ('consumer_secret', models.CharField(max_length=40)),
                ('access_token_key', models.CharField(max_length=40)),
                ('access_token_secret', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Twitter Config',
                'verbose_name_plural': 'Twitter Config',
            },
        ),
        migrations.CreateModel(
            name='RSSEntries',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rssid', models.CharField(max_length=200, verbose_name='ID')),
                ('published', models.DateTimeField(verbose_name='Published')),
                ('update', models.DateTimeField(verbose_name='Updated')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('is_saved', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snotra_rss.RSSFeeds')),
            ],
            options={
                'verbose_name': 'RSS Entry',
                'verbose_name_plural': 'RSS Entries',
            },
        ),
    ]
