# Generated by Django 2.2 on 2019-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snotra_rss', '0002_auto_20190420_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeeds',
            name='twit',
            field=models.BooleanField(default=False),
        ),
    ]
