# Generated by Django 2.1.5 on 2019-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snotra_rss', '0002_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeeds',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
