# Generated by Django 2.2.1 on 2019-05-30 12:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('snotra_rss', '0003_rssfeeds_twit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssentries',
            name='tag',
        ),
        migrations.CreateModel(
            name='RSSEntriesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='snotra_rss.RSSEntries')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snotra_rss_rssentriestag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rssentries',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='snotra_rss.RSSEntriesTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
